### ISSUE TITLE
Force Sync Up

### ISSUE THREAD

**Issue by bbakermmc** [JvSomeren/tautulli-watched-sync#4]
Is there a way to force a push to get trakt re in sync.  IE resync missing watched status

**Comment by JvSomeren** [comment]
The script as it exists now only has a one-way sync from Tautulli to Trakt. Since it triggers based on Tautulli's notification agent I haven't found a way to force a sync besides manually watching beyond the watched threshold.
Perhaps you could adapt part of the script to sync based on the history Tautulli stores.
